### ISSUE TITLE
Grid - Column Moving Sample throws error in console when clicking on pin icon in column header of pinned column

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-blazor-examples#308]
goto grid - column moving options, 
open dev tools 
click the red pin in the header of one of the pinned columns

Result:
Uncaught DOMException: Failed to execute 'setPointerCapture' on 'Element': InvalidStateError
    at Hq.onPointerDown (https://localhost:44317/_content/IgniteUI.Blazor/igniteui-angular-elements.6626527c16f60817a0fa.bundle.js:2:567221)
    at Hq.onPointerDown (https://localhost:44317/_content/IgniteUI.Blazor/igniteui-angular-elements.6626527c16f60817a0fa.bundle.js:2:1515342)
    at t._next (https://localhost:44317/_content/IgniteUI.Blazor/igniteui-angular-elements.6626527c16f60817a0fa.bundle.js:2:562541)
    at t.__tryOrUnsub (https://localhost:44317/_content/IgniteUI.Blazor/igniteui-angular-elements.6626527c16f60817a0fa.bundle.js:2:60772)
    at t.next (https://localhost:44317/_content/IgniteUI.Blazor/igniteui-angular-elements.6626527c16f60817a0fa.bundle.js:2:59937)
    at t._next (https://localhost:44317/_content/IgniteUI.Blazor/igniteui-angular-elements.6626527c16f60817a0fa.bundle.js:2:59034)
    at t.next (https://localhost:44317/_content/IgniteUI.Blazor/igniteui-angular-elements.6626527c16f60817a0fa.bundle.js:2:58705)
    at t._next (https://localhost:44317/_content/IgniteUI.Blazor/igniteui-angular-elements.6626527c16f60817a0fa.bundle.js:2:59034)
    at t.next (https://localhost:44317/_content/IgniteUI.Blazor/igniteui-angular-elements.6626527c16f60817a0fa.bundle.js:2:58705)
    at HTMLElement.<anonymous> (https://localhost:44317/_content/IgniteUI.Blazor/igniteui-angular-elements.6626527c16f60817a0fa.bundle.js:2:82092)

**Comment by HUSSAR-mtrela** [comment]
@agoldenbaum check if this is an issue in sample or product
