### ISSUE TITLE
Grid samples throws errors after pressing clear sorting

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-blazor-examples#311]
goto: https://www.infragistics.com/blazor-client/samples/grids/grid-column-sorting-options
press Clear Sorting:

error in console:
Uncaught TypeError: Cannot read properties of null (reading 'i')
    at w.q (app.90f367bcb954b825e300.bundle.js:2:85469)
    at w.u (app.90f367bcb954b825e300.bundle.js:2:86441)
    at w.r (app.90f367bcb954b825e300.bundle.js:2:85715)
    at w.q (app.90f367bcb954b825e300.bundle.js:2:85553)
    at w.t (app.90f367bcb954b825e300.bundle.js:2:81881)
    at c.g (igniteui-webcomponents-layouts.41f56f8590a7bc4ab508.bundle.js:1:29866)
    at M.b4 (igniteui-webcomponents-layouts.41f56f8590a7bc4ab508.bundle.js:1:86666)
    at M.dv (igniteui-webcomponents-layouts.41f56f8590a7bc4ab508.bundle.js:1:85581)
    at M.cd (igniteui-webcomponents-layouts.41f56f8590a7bc4ab508.bundle.js:1:85417)
    at N.n [as c] (app.90f367bcb954b825e300.bundle.js:2:269705)

**Comment by IGvaleries** [comment]
same issue happens if first adding a group then pressing "Clear grouped Columns"

**Comment by HUSSAR-mtrela** [comment]
fixed on staging
https://staging.infragistics.com/blazor-client/samples/grids/grid-column-sorting-options
