### ISSUE TITLE
Grid RowDragbase through console error 

### ISSUE THREAD

**Issue by igDivya** [IgniteUI/igniteui-blazor-examples#342]
Click 6 dot icon

https://staging.infragistics.com/webcomponents-demos/samples/grids/grid/row-drag-base

**Comment by igDivya** [comment]
attached image also -
![image](https://user-images.githubusercontent.com/22081100/230923404-5252a68e-5cd7-4220-91ef-9d3caf85dea3.png)


"Uncaught TypeError: Cannot read properties of undefined (reading 'getBoundingClientRect')
    at r.onGridRowDragEnd (68785.65e03d8d.chunk.js:1:10423)
    at c.invokeTask (89705.65e03d8d.chunk.js:2:28273)
    at t.runTask (89705.65e03d8d.chunk.js:2:23647)
    at d.invokeTask [as invoke] (89705.65e03d8d.chunk.js:2:29343)
    at g (89705.65e03d8d.chunk.js:2:41723)
    at u (89705.65e03d8d.chunk.js:2:42017)
    at s.p (89705.65e03d8d.chunk.js:2:42277)
    at t._next (89705.65e03d8d.chunk.js:2:2420857)
    at t.__tryOrUnsub (89705.65e03d8d.chunk.js:2:60251)
    at t.next (89705.65e03d8d.chunk.js:2:59416)
onGridRowDragEnd @ 68785.65e03d8d.chunk.js:1
invokeTask @ 89705.65e03d8d.chunk.js:2
runTask @ 89705.65e03d8d.chunk.js:2
invokeTask @ 89705.65e03d8d.chunk.js:2
g @ 89705.65e03d8d.chunk.js:2
u @ 89705.65e03d8d.chunk.js:2
p @ 89705.65e03d8d.chunk.js:2
(anonymous) @ 89705.65e03d8d.chunk.js:2
t.__tryOrUnsub @ 89705.65e03d8d.chunk.js:2
t.next @ 89705.65e03d8d.chunk.js:2
t._next @ 89705.65e03d8d.chunk.js:2
t.next @ 89705.65e03d8d.chunk.js:2
t.notifyNext @ 89705.65e03d8d.chunk.js:2
t._next @ 89705.65e03d8d.chunk.js:2
t.next @ 89705.65e03d8d.chunk.js:2
t.notifyNext @ 89705.65e03d8d.chunk.js:2
t._next @ 89705.65e03d8d.chunk.js:2
t.next @ 89705.65e03d8d.chunk.js:2
t._next @ 89705.65e03d8d.chunk.js:2
t.next @ 89705.65e03d8d.chunk.js:2
t.__tryOrUnsub @ 89705.65e03d8d.chunk.js:2
t.next @ 89705.65e03d8d.chunk.js:2
t._next @ 89705.65e03d8d.chunk.js:2
t.next @ 89705.65e03d8d.chunk.js:2
t.next @ 89705.65e03d8d.chunk.js:2
emit @ 89705.65e03d8d.chunk.js:2
(anonymous) @ 89705.65e03d8d.chunk.js:2
invoke @ 89705.65e03d8d.chunk.js:2
onInvoke @ 89705.65e03d8d.chunk.js:2
invoke @ 89705.65e03d8d.chunk.js:2
run @ 89705.65e03d8d.chunk.js:2
run @ 89705.65e03d8d.chunk.js:2
onPointerUp @ 89705.65e03d8d.chunk.js:2
(anonymous) @ 89705.65e03d8d.chunk.js:2
t.__tryOrUnsub @ 89705.65e03d8d.chunk.js:2
t.next @ 89705.65e03d8d.chunk.js:2
t._next @ 89705.65e03d8d.chunk.js:2
t.next @ 89705.65e03d8d.chunk.js:2
t._next @ 89705.65e03d8d.chunk.js:2
t.next @ 89705.65e03d8d.chunk.js:2
(anonymous) @ 89705.65e03d8d.chunk.js:2
invokeTask @ 89705.65e03d8d.chunk.js:2
runTask @ 89705.65e03d8d.chunk.js:2
invokeTask @ 89705.65e03d8d.chunk.js:2
g @ 89705.65e03d8d.chunk.js:2
u @ 89705.65e03d8d.chunk.js:2
p @ 89705.65e03d8d.chunk.js:2"

**Comment by HUSSAR-mtrela** [comment]
@igDivya your screenshot shows am issue in WC and this is Blazor repo. Does this issue occur in both WC/Blazor or just in WC samples? If this is WC issue than it should be submitted in https://github.com/IgniteUI/igniteui-wc-examples

**Comment by igDivya** [comment]
Issue is in Blazor also:
![image](https://user-images.githubusercontent.com/22081100/230926553-83800deb-5807-41d9-98c6-538cdac52b3f.png)
